#pragma once

#include "SimpleFlashFsVfs.h"
#include <thread>
#include <atomic>
#include <mutex>
#include <list>
#include <map>
#include <string>
#include <expected>

namespace SimpleFlashFs::Vfs
{

class SimpleFlashFsVfsServer : public VfsServerInterface
{
public:
    // AI generated by GitHub Copilot Claude Opus 4.7 START
    // OpenFile is the per-physical-file shared state. Each call to
    // open() returns a fresh ThreadedFileHandle that holds a
    // shared_ptr<OpenFile>. When the last ThreadedFileHandle for a
    // given path goes out of scope, the OpenFile is destroyed which
    // in turn destroys the underlying drive file_handle_t and
    // (implicitly through the FileHandle dtor) flushes the file.
    //
    // The implementation is intentionally opaque (forward-declared
    // here, defined inside the .cc) so the rest of the world does
    // not need to see the std::mutex member or the FileInterface
    // implementation details.
    struct OpenFile;
    // AI generated by GitHub Copilot Claude Opus 4.7 END

private:
    mutable std::mutex                              m_mutex;
    std::atomic<bool>                               m_running {false};
    std::list<std::shared_ptr<VfsDriveInterface>>   m_drives {};
    std::string                                     m_current_drive {};

    // AI generated by GitHub Copilot Claude Opus 4.7 START
    // Open-file table: lets several open() calls on the same path
    // share one underlying drive file handle so concurrent
    // read/write/append/truncate calls cannot corrupt each other.
    //
    // Keyed by `drive_name + ":" + file_path` so equivalent paths
    // (with or without a leading slash, with or without an explicit
    // drive) map to the same entry as long as they refer to the
    // same physical file.
    //
    // weak_ptr lets the entry self-evict the moment all openers
    // release their shared_ptrs - we just opportunistically purge
    // expired entries inside cleanup() so the map stays bounded.
    //
    // Guarded by m_mutex (same lock that protects m_drives) since
    // open() touches both anyway.
    std::map<std::string, std::weak_ptr<OpenFile>>  m_open_files {};
    // AI generated by GitHub Copilot Claude Opus 4.7 END

public:
    SimpleFlashFsVfsServer();
    ~SimpleFlashFsVfsServer();

    bool register_drive( std::shared_ptr<VfsDriveInterface> drive ) override;

    file_handle_t open( const std::string_view & path, std::ios_base::openmode mode ) override;
    bool list_files( list_files_callback_t callback, const std::string_view & drive_name ) override;
    std::vector<std::string_view> get_drive_names() const override;

    void create( const std::string_view & drive_name ) override;

    std::string get_current_drive() const override;
    bool set_current_drive( const std::string_view & drive_name ) override;

    void cleanup() override;

    std::expected<bool, std::string_view> is_drive_initialized( const std::string_view & drive_name ) const override;

private:
    std::string_view get_drive_name( const std::string_view & path ) const;
    std::string_view parse_drive_name( std::string_view & path ) const;

    // AI generated by GitHub Copilot Claude Opus 4.7 START
    // Drop every entry in m_open_files whose weak_ptr has expired.
    // Caller must already hold m_mutex.
    void purge_expired_open_files();
    // AI generated by GitHub Copilot Claude Opus 4.7 END
};

} // namespace SimpleFlashFs::Vfs