#include "SimpleFlashFsVfsServer.h"
#include <CpputilsDebug.h>
#include <format.h>

using namespace SimpleFlashFs::Vfs;

// AI generated by GitHub Copilot Claude Opus 4.7 START
// OpenFile: the entry in m_open_files. One per physical open file.
// Holds the (sole) underlying drive file handle plus a mutex that
// serialises every read/write/flush/truncate on that handle.
//
// Defined out-of-line (rather than as a nested type in the header)
// so the header stays lightweight. The class declaration in the
// header only forward-declares this type.
struct SimpleFlashFs::Vfs::SimpleFlashFsVfsServer::OpenFile
{
    SimpleFlashFs::Vfs::file_handle_t   handle;
    mutable std::mutex                  mutex;

    explicit OpenFile( SimpleFlashFs::Vfs::file_handle_t h )
    : handle( std::move(h) )
    {}
};
// AI generated by GitHub Copilot Claude Opus 4.7 END

namespace {

// AI generated by GitHub Copilot Claude Opus 4.7 START
// ThreadedFileHandle: returned to callers of VfsServerInterface::open().
// Multiple ThreadedFileHandles can share the same OpenFile (and thus
// the same underlying drive handle) when open() is called repeatedly
// for the same path. Each ThreadedFileHandle keeps its OWN cursor
// (m_pos) and its own append flag so the openers do not stomp on
// each other's read/write position.
//
// Every operation on the shared underlying handle is performed under
// the OpenFile's mutex; the underlying handle is seek()ed to m_pos
// (or to file_size() for append writes) just before each call so the
// shared handle's internal position stays consistent with what this
// opener expects.
//
// Read paths in the base FS are lock-free; the per-OpenFile mutex
// here serialises CALLS to the FS for a single file but does not
// serialise calls for different files. The base FS's own fine-grained
// locks (m_inode_meta_mutex / m_free_data_pages_mutex / m_mem_mutex)
// keep cross-file operations safe.
class ThreadedFileHandle : public SimpleFlashFs::FileInterface
{
private:
    using OpenFile = SimpleFlashFs::Vfs::SimpleFlashFsVfsServer::OpenFile;

    std::shared_ptr<OpenFile>   m_entry;
    std::size_t                 m_pos    = 0;
    bool                        m_append = false;

    // Convenience: dereferenced underlying handle. Caller must hold
    // m_entry->mutex.
    SimpleFlashFs::FileInterface & uh() const { return *m_entry->handle; }
    bool                            uh_ok() const { return m_entry && m_entry->handle && !!*m_entry->handle; }

public:
    ThreadedFileHandle( std::shared_ptr<OpenFile> entry,
                        std::ios_base::openmode   mode )
    : m_entry ( std::move(entry) ),
      m_pos   ( 0 ),
      m_append( (mode & std::ios::app) != 0 )
    {
        // ios::ate -> start the per-handle cursor at the end of the
        // file as observed RIGHT NOW. Subsequent writes by another
        // opener will be invisible to this cursor until we re-seek.
        if( (mode & std::ios::ate) != 0 ) {
            std::lock_guard l( m_entry->mutex );
            if( uh_ok() ) {
                m_pos = uh().file_size();
            }
        }
    }

    bool operator!() const override {
        return !uh_ok();
    }

    std::size_t write( const std::byte *data, std::size_t size ) override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return 0;
        }
        const std::size_t target = m_append ? uh().file_size() : m_pos;
        if( uh().tellg() != target ) {
            uh().seek( target );
        }
        const std::size_t n = uh().write( data, size );
        m_pos = uh().tellg();
        return n;
    }

    std::size_t read( std::byte *data, std::size_t size ) override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return 0;
        }
        if( uh().tellg() != m_pos ) {
            uh().seek( m_pos );
        }
        const std::size_t n = uh().read( data, size );
        m_pos = uh().tellg();
        return n;
    }

    bool flush() override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return false;
        }
        return uh().flush();
    }

    // Per-handle cursor; no need to touch the shared handle.
    std::size_t tellg() const override {
        return m_pos;
    }

    std::size_t file_size() const override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return 0;
        }
        return uh().file_size();
    }

    bool eof() const override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return true;
        }
        const std::size_t sz = uh().file_size();
        if( sz == 0 ) return true;
        return m_pos >= sz;
    }

    bool seek( std::size_t pos_ ) override {
        // Pure per-handle change; we re-sync the shared handle on
        // the next read/write so two openers can keep independent
        // cursors without thrashing the underlying handle.
        m_pos = pos_;
        return true;
    }

    bool delete_file() override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return false;
        }
        // After this the underlying handle is disconnected
        // (fs == nullptr inside FileHandle). Sibling openers will
        // see operator!() == true and their next read/write/flush
        // will return 0/false instead of crashing.
        return uh().delete_file();
    }

    bool rename_file( const std::string_view & new_file_name ) override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return false;
        }
        return uh().rename_file( new_file_name );
    }

    bool truncate( std::size_t new_size ) override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return false;
        }
        const bool ok = uh().truncate( new_size );
        if( ok && m_pos > new_size ) {
            m_pos = new_size;
        }
        return ok;
    }

    std::string_view get_file_name() const override {
        std::lock_guard l( m_entry->mutex );
        if( !uh_ok() ) {
            return {};
        }
        return uh().get_file_name();
    }

    bool is_append_mode() const override {
        // append is per-handle metadata, no need to lock.
        return m_append;
    }
};
// AI generated by GitHub Copilot Claude Opus 4.7 END

} // namespace

SimpleFlashFsVfsServer::SimpleFlashFsVfsServer()
: SimpleFlashFsVfsServer::VfsServerInterface()
{
}

SimpleFlashFsVfsServer::~SimpleFlashFsVfsServer()
{

}

bool SimpleFlashFsVfsServer::register_drive( std::shared_ptr<VfsDriveInterface> drive )
{
    auto lock = std::scoped_lock(m_mutex);
    m_drives.push_back( drive );
    return true;
}

file_handle_t SimpleFlashFsVfsServer::open( const std::string_view & path, std::ios_base::openmode mode )
{
    std::string_view file_path = path;
    const auto drive_name = parse_drive_name( file_path );

    // CPPDEBUG( Tools::format( "open file: %s at drive: %s", file_path, drive_name ) );

    auto lock = std::scoped_lock(m_mutex);

    // AI generated by GitHub Copilot Claude Opus 4.7 START
    // Build a normalised key so "/a/foo" and "a/foo" map to the same
    // entry. parse_drive_name has already stripped the drive prefix
    // and any leading slash from file_path.
    std::string key;
    key.reserve( drive_name.size() + 1 + file_path.size() );
    key.append( drive_name ).append( ":" ).append( file_path );

    // Step 1: is the file already open by another handle?
    if( auto it = m_open_files.find( key ); it != m_open_files.end() ) {
        if( auto entry = it->second.lock(); entry && entry->handle && !!*entry->handle ) {
            // Yes - reuse the shared OpenFile.
            //
            // If the caller asked for trunc, propagate it now so that
            // BOTH openers see the empty file. This matches
            // POSIX-ish semantics for O_TRUNC on an already-open file.
            if( (mode & std::ios::trunc) != 0 ) {
                std::lock_guard h_lock( entry->mutex );
                if( !!*entry->handle ) {
                    entry->handle->truncate( 0 );
                }
            }
            return std::make_unique<ThreadedFileHandle>( std::move(entry), mode );
        }
        // weak_ptr expired (or handle is disconnected) - drop the
        // stale entry and fall through to fresh open.
        m_open_files.erase( it );
    }

    // Step 2: first opener for this path. Find the drive and open
    // the file the traditional way.
    bool drive_found = false;

    for( auto & drive : m_drives ) {
        if( drive->get_drive_name() != drive_name ) {
            continue;
        }

        drive_found = true;

        if( !drive->initialized() ) {
            if( !drive->init() ) {
                return {};
            }
        }

        auto file = drive->open( file_path, mode );
        if( file ) {
            // Move the unique_ptr<FileInterface> into an OpenFile
            // and store a weak_ptr in the table.
            auto entry = std::make_shared<OpenFile>( std::move(file) );
            m_open_files[ key ] = entry;
            return std::make_unique<ThreadedFileHandle>( std::move(entry), mode );
        }
    }
    // AI generated by GitHub Copilot Claude Opus 4.7 END

    if( !drive_found ) {
        CPPDEBUG( Tools::format( "drive not found: %s", drive_name ) );
    } else {
        CPPDEBUG( Tools::format( "file not found: %s at drive: %s", file_path, drive_name ) );
    }

    return {};
}

std::string_view SimpleFlashFsVfsServer::get_drive_name( const std::string_view & path ) const
{
    std::string_view drive_name = path;

    if( drive_name.starts_with('/') ) {
        drive_name.remove_prefix(1);
    }

    const auto pos = drive_name.find( '/' );

    if( pos != std::string_view::npos ) {
        return drive_name.substr( 0, pos );
    }
    return drive_name;
}

std::string_view SimpleFlashFsVfsServer::parse_drive_name( std::string_view & path ) const
{
    std::string_view            drive_name = path;
    std::string_view::size_type file_name_start_pos = 0;

    if( drive_name.starts_with('/') ) {
        drive_name.remove_prefix(1);
        file_name_start_pos++;
    }

    const auto pos = drive_name.find( '/' );

    if( pos != std::string_view::npos ) {
        path.remove_prefix(pos + file_name_start_pos);

        if( path.starts_with('/') ) {
            path.remove_prefix(1);
        }

        return drive_name.substr( 0, pos );
    }
    return drive_name;
}

std::vector<std::string_view> SimpleFlashFsVfsServer::get_drive_names() const
{
    auto lock = std::scoped_lock(m_mutex);
    std::vector<std::string_view> drive_names;
    for( auto & drive : m_drives ) {
        drive_names.push_back( drive->get_drive_name() );
    }
    return drive_names;
}

bool SimpleFlashFsVfsServer::list_files( list_files_callback_t callback, const std::string_view & drive_name )
{
    auto lock = std::scoped_lock(m_mutex);
    for( auto & drive : m_drives ) {

        if( !drive_name.empty() && drive->get_drive_name() != drive_name ) {
            continue;
        }

        if( !drive->initialized() ) {
            if( !drive->init() ) {
                continue;
            }
        }

        if( !drive->list_files( callback ) ) {
            return false;
        }
    }
    return true;
}

void SimpleFlashFsVfsServer::create( const std::string_view & drive_name )
{
    auto lock = std::scoped_lock(m_mutex);
    for( auto & drive : m_drives ) {
        if( drive->get_drive_name() == drive_name ) {
            drive->create();
            return;
        }
    }
}

std::string SimpleFlashFsVfsServer::get_current_drive() const
{
    auto lock = std::scoped_lock(m_mutex);
    return m_current_drive;
}

bool SimpleFlashFsVfsServer::set_current_drive( const std::string_view & drive_name )
{
    auto lock = std::scoped_lock(m_mutex);
    
    // Check if the drive exists
    for( auto & drive : m_drives ) {
        if( drive->get_drive_name() == drive_name ) {
            m_current_drive = std::string(drive_name);

            if( !drive->initialized() ) {
                if( !drive->init() ) {
                    return false;
                }
            }

            return true;
        }
    }
    
    return false;
}

void SimpleFlashFsVfsServer::cleanup()
{
    auto lock = std::scoped_lock(m_mutex);
    for( auto & drive : m_drives ) {
        drive->cleanup();
    }
    // AI generated by GitHub Copilot Claude Opus 4.7 START
    // Reap any open-file table entries whose last shared_ptr was
    // released since the previous cleanup. Without this the map
    // would slowly grow with stale weak_ptr placeholders.
    purge_expired_open_files();
    // AI generated by GitHub Copilot Claude Opus 4.7 END
}

// AI generated by GitHub Copilot Claude Opus 4.7 START
void SimpleFlashFsVfsServer::purge_expired_open_files()
{
    // Caller must already hold m_mutex.
    for( auto it = m_open_files.begin(); it != m_open_files.end(); ) {
        if( it->second.expired() ) {
            it = m_open_files.erase( it );
        } else {
            ++it;
        }
    }
}
// AI generated by GitHub Copilot Claude Opus 4.7 END