/*
 * SimpleFlashFsFlashMemoryInterface.h
 *
 *  Created on: 25.12.2023
 *      Author: martin
 */

#pragma once
#include <cstddef>
#include <string>
#include <fstream>
#include <span>

namespace SimpleFlashFs {

class FileInterface
{
public:
	virtual ~FileInterface() {}

	virtual bool operator!() const = 0;

	virtual std::size_t write( const std::byte *data, std::size_t size ) = 0;

	std::size_t write( const std::span<const std::byte> & data ) {
		return write( data.data(), data.size() );
	}

	virtual std::size_t read( std::byte *data, std::size_t size ) = 0;

	virtual bool flush() = 0;

	virtual std::size_t tellg() const = 0;

	virtual std::size_t file_size() const = 0;

	virtual bool eof() const = 0;

	virtual bool seek( std::size_t pos_ ) = 0;

	virtual bool delete_file() = 0;

	virtual bool rename_file( const std::string_view & new_file_name ) = 0;

	// AI generated by GitHub Copilot Claude Opus 4.7 START
	/**
	 * Truncate the file to `new_size` bytes. Default implementation
	 * returns false; concrete FileInterface implementations that can
	 * shrink their backing store should override this.
	 *
	 * Used by SimpleIni when a value shrinks so the file size matches
	 * the new content size instead of being padded with whitespace.
	 */
	virtual bool truncate( std::size_t /*new_size*/ ) {
		return false;
	}
	// AI generated by GitHub Copilot Claude Opus 4.7 END

	// comfort functions

	bool valid() const {
		return !operator!();
	}

	virtual std::string_view get_file_name() const = 0;

	virtual bool is_append_mode() const = 0;
};


} // namespace SimpleFlashFs

