/**
 * SimpleFlashFs locking primitives.
 *
 * Provides a NullMutex that satisfies the C++ BasicLockable concept
 * but is a complete no-op. It exists so that the static / single-
 * threaded Config can plug into the same template machinery as the
 * dynamic / multi-threaded Config without paying any runtime cost.
 *
 * AI generated by GitHub Copilot Claude Opus 4.7 START
 *  Created on: 12.06.2026
 * AI generated by GitHub Copilot Claude Opus 4.7 END
 */

#ifndef SRC_BASE_SIMPLEFLASHFSLOCK_H_
#define SRC_BASE_SIMPLEFLASHFSLOCK_H_

namespace SimpleFlashFs {

// AI generated by GitHub Copilot Claude Opus 4.7 START
/**
 * NullMutex: a no-op mutex implementation.
 *
 * Satisfies the BasicLockable named requirement (lock() and unlock())
 * and additionally provides try_lock() so it also matches Lockable.
 * Used as Config::mutex_type for single-threaded / embedded builds
 * where adding real mutexes would only waste RAM and code space.
 *
 * `std::lock_guard<NullMutex>` compiles down to nothing, so all the
 * locking calls scattered through SimpleFlashFsBase are completely
 * elided in the static_memory build.
 */
struct NullMutex
{
	constexpr void lock()     noexcept {}
	constexpr void unlock()   noexcept {}
	constexpr bool try_lock() noexcept { return true; }
};
// AI generated by GitHub Copilot Claude Opus 4.7 END

} // namespace SimpleFlashFs

#endif /* SRC_BASE_SIMPLEFLASHFSLOCK_H_ */
